spring.application.name=demo
server.port=8080

# Tắt cache để sửa template không cần restart
spring.thymeleaf.cache=false

# Cấu hình online/offline cho Bootstrap (true: dùng offline từ static/vendor)
app.bootstrap.offline=true

# ===== SQL Server =====
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ThymeleafDemo;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sa

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Map mọi String -> NVARCHAR để lưu được tiếng Việt
spring.jpa.properties.hibernate.use_nationalized_character_data=true
spring.jpa.open-in-view=false

# ===== i18n =====
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false
